service: nasa-daily-image

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      -schedule : cron(0 12 * * ? 0)
    environment:
      NASA_API_KEY:
      TWILIO_ACCOUNT_SID: 
      TWILIO_AUTH_TOKEN : 
      TWILIO_PHONE_NUMBER : 
      MY_PHONE_NUMBER : +1123456789

configValidationMode: error
